---

- name: SONiC Management Framework REST API examples
  hosts: all
  gather_facts: no
  connection: httpapi
  tasks:
    - name: Perform PUT operation to add a VLAN network instance
      dellemc.enterprise_sonic.sonic_api:
        url: data/openconfig-network-instance:network-instances/network-instance=Vlan116
        method: "PUT"
        body: {"openconfig-network-instance:network-instance": [{"name": "Vlan116","config": {"name": "Vlan116"}}]}
        status_code: 204
    - name: Perform GET operation to view VLAN network instance
      dellemc.enterprise_sonic.sonic_api:
        url: data/openconfig-network-instance:network-instances/network-instance=Vlan116
        method: "GET"
        status_code: 200
      register: api_op
